name: joins
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.2

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  carousel_slider: ^4.0.0-nullsafety.0
  time_planner: ^0.0.4

  getwidget: ^3.0.1
  vertical_card_pager: ^1.4.0
  pie_chart: ^5.3.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  lottie: ^2.0.0
  cloud_firestore: ^3.5.1




 

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  -  Assets/Images/